### ISSUE TITLE
Got error on test_data.classes

### ISSUE THREAD

**Issue by TeTeTang** [bentrevett/pytorch-image-classification#12]
The AttributeError: 'Subset' object has no attribute 'classes' was returned for 
"output_dim = len(data_process.test_data.classes)"

**Comment by bentrevett** [comment]
Which cell in which notebook is giving you this error?

**Comment by TeTeTang** [comment]
ResNet.ipynb. I do not have the cell number, I pasted a screenshot for that cell though.

[Graphical user interface, text, application, email  Description automatically generated]
--
Regards,

Pingjie Tang

From: Ben Trevett ***@***.***>
Date: Monday, June 14, 2021 at 5:55 AM
To: bentrevett/pytorch-image-classification ***@***.***>
Cc: Tang, Pingjie ***@***.***>, Author ***@***.***>
Subject: Re: [bentrevett/pytorch-image-classification] Got error on test_data.classes (#12)

Which cell in which notebook is giving you this error?

**Comment by TeTeTang** [comment]
The issue was fixed.
