### ISSUE TITLE
LeNet: Small typo in comments

### ISSUE THREAD

**Issue by maulikchevli** [bentrevett/pytorch-image-classification#3]
Hello,
Thank you for writing these amazing tutorials!

I found a typo in LeNet's forward method: `#x = [batch size, 100]`
Output features for first linear layer in the code are 120.

```
        x = x.view(x.shape[0], -1)
        
        #x = [batch size, 16*4*4 = 256]
        
        h = x
        
        x = self.fc_1(x)
        
        #x = [batch size, 100]
        
        x = F.relu(x)
```

**Comment by bentrevett** [comment]
Glad you found the tutorials helpful. Thanks for spotting the typo, will fix now.
